import type { Product, FooterLink } from "@/types"

export const footerLinks: FooterLink[] = [
    {
        name: "Home",
        url: "/"
    },
    {
        name: "Shop",
        url: "/shop"
    },
    {
        name: "Contact",
        url: "/contact"
    },
    {
        name: "Admin",
        url: "/admin/login"
    }
]

export const products: Product[] = [
    // ================= FEATURED (8) =================
    {
        id: "550e8400-e29b-41d4-a716-446655440000",
        name: "Nike Air Jordan 1",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget finibus lectus, a condimentum neque. Donec egestas est ut nunc posuere, vitae bibendum enim egestas.",
        price: 1500,
        images: ["/images/nike_shoe_1.png", "/images/adidas_shoe_1.png", "/images/nb_shoe_1.png", "/images/nike_dunk_1.png"],
        colors: ["#FF4444", "#4444FF", "#F5F5F5", "#1A1A1A"],
        sizes: ["36", "37", "38", "39", "40"],
        brand: { id: "b1", name: "Nike", logoUrl: "" },
        brandId: "b1",
        categoryId: "740e8400-e29b-41d4-a716-446655440000",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 10
    },
    {
        id: "550e8400-e29b-41d4-a716-446655440001",
        name: "Adidas Yeezy Boost",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget finibus lectus, a condimentum neque. Donec egestas est ut nunc posuere, vitae bibendum enim egestas.",
        price: 1800,
        images: ["/images/adidas_shoe_1.png", "/images/nike_shoe_1.png", "/images/nb_shoe_1.png", "/images/nike_dunk_1.png"],
        colors: ["#F5E6BE", "#1A1A1A", "#FF4444"],
        sizes: ["37", "38", "39", "40"],
        brand: { id: "b2", name: "Adidas", logoUrl: "" },
        brandId: "b2",
        categoryId: "740e8400-e29b-41d4-a716-446655440000",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 6
    },
    {
        id: "3",
        name: "New Balance 2002R",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget finibus lectus, a condimentum neque. Donec egestas est ut nunc posuere, vitae bibendum enim egestas.",
        price: 1300,
        images: ["/images/nb_shoe_1.png", "/images/nike_shoe_1.png", "/images/adidas_shoe_1.png", "/images/nike_dunk_1.png"],
        colors: ["#B3B3B3", "#1A1A1A", "#4444FF"],
        sizes: ["38", "39", "40", "41"],
        brand: { id: "b3", name: "New Balance", logoUrl: "" },
        brandId: "b3",
        categoryId: "c1",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 8
    },
    {
        id: "4",
        name: "Nike Dunk Low Panda",
        description: "The classic black and white colorway that goes with everything. Features premium leather and a comfortable rubber outsole.",
        price: 1100,
        images: ["/images/nike_dunk_1.png", "/images/nike_shoe_1.png", "/images/adidas_shoe_1.png", "/images/nb_shoe_1.png"],
        colors: ["#FFFFFF", "#000000", "#FF4444"],
        sizes: ["36", "37", "38", "39", "40", "41", "42"],
        brand: { id: "b4", name: "Nike SB", logoUrl: "" },
        brandId: "b4",
        categoryId: "c1",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 12
    },
    {
        id: "5",
        name: "Essentials Hoodie",
        description: "Minimalist oversized hoodie.",
        price: 650,
        images: ["/images/hero-bg.png"],
        colors: ["#222222"],
        sizes: ["M", "L"],
        brand: { id: "b5", name: "Essentials", logoUrl: "" },
        brandId: "b5",
        categoryId: "c2",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 20
    },
    {
        id: "6",
        name: "Tech Fleece Jogger",
        description: "Lightweight warmth with modern fit.",
        price: 500,
        images: ["/images/hero-bg.png"],
        colors: ["#1C1C1C"],
        sizes: ["S", "M", "L"],
        brand: { id: "b6", name: "Nike Sportswear", logoUrl: "" },
        brandId: "b6",
        categoryId: "c2",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 14
    },
    {
        id: "7",
        name: "Streetwear Hoodie",
        description: "Everyday essential hoodie.",
        price: 580,
        images: ["/images/hero-bg.png"],
        colors: ["#B3B3B3"],
        sizes: ["M", "L"],
        brand: { id: "b7", name: "Urban Supply", logoUrl: "" },
        brandId: "b7",
        categoryId: "c2",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 16
    },
    {
        id: "8",
        name: "Lifestyle Sneaker",
        description: "Comfort-focused daily sneaker.",
        price: 900,
        images: ["/images/nike_shoe_1.png"],
        colors: ["#FFFFFF"],
        sizes: ["US 9", "US 10"],
        brand: { id: "b8", name: "Street Core", logoUrl: "" },
        brandId: "b8",
        categoryId: "c1",
        isFeatured: true,
        isNewArrival: false,
        isPromotion: false,
        stock: 9
    },

    // ================= NEW ARRIVALS (8) =================
    {
        id: "9",
        name: "Modern Runner",
        description: "Sleek and responsive running shoe designed for modern athletes. Features breathable mesh and advanced foam technology.",
        price: 1200,
        images: ["/images/adidas_shoe_1.png", "/images/nike_shoe_1.png", "/images/nb_shoe_1.png"],
        colors: ["#FFFFFF", "#4444FF", "#1A1A1A"],
        sizes: ["38", "39", "40", "41", "42"],
        brand: { id: "b9", name: "RunLab", logoUrl: "" },
        brandId: "b9",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 7
    },
    {
        id: "10",
        name: "Classic Retro",
        description: "Old-school silhouette with modern materials.",
        price: 1150,
        images: ["/images/nb_shoe_1.png"],
        colors: ["#B3B3B3"],
        sizes: ["US 9", "US 10"],
        brand: { id: "b10", name: "Retro Lab", logoUrl: "" },
        brandId: "b10",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 6
    },
    {
        id: "11",
        name: "Minimal Hoodie",
        description: "Clean design premium hoodie.",
        price: 600,
        images: ["/images/hero-bg.png"],
        colors: ["#F5E6BE"],
        sizes: ["S", "M"],
        brand: { id: "b11", name: "Mono Wear", logoUrl: "" },
        brandId: "b11",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 18
    },
    {
        id: "12",
        name: "Urban Low Top",
        description: "Low-top sneaker for daily wear.",
        price: 980,
        images: ["/images/nike_dunk_1.png"],
        colors: ["#000000"],
        sizes: ["US 8", "US 9"],
        brand: { id: "b12", name: "City Steps", logoUrl: "" },
        brandId: "b12",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 11
    },
    {
        id: "13",
        name: "Everyday Jogger",
        description: "Comfort-first jogger pants.",
        price: 420,
        images: ["/images/hero-bg.png"],
        colors: ["#1C1C1C"],
        sizes: ["M", "L"],
        brand: { id: "b13", name: "Daily Fit", logoUrl: "" },
        brandId: "b13",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 15
    },
    {
        id: "14",
        name: "Performance Trainer",
        description: "Designed for long wear comfort.",
        price: 1250,
        images: ["/images/adidas_shoe_1.png"],
        colors: ["#FFFFFF"],
        sizes: ["US 9", "US 10"],
        brand: { id: "b14", name: "ProMotion", logoUrl: "" },
        brandId: "b14",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 8
    },
    {
        id: "15",
        name: "Relaxed Hoodie",
        description: "Soft fleece relaxed fit hoodie.",
        price: 550,
        images: ["/images/hero-bg.png"],
        colors: ["#B3B3B3"],
        sizes: ["M", "L"],
        brand: { id: "b15", name: "Cloud Wear", logoUrl: "" },
        brandId: "b15",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 19
    },
    {
        id: "16",
        name: "Street Classic",
        description: "Timeless everyday sneaker.",
        price: 1000,
        images: ["/images/nike_shoe_1.png"],
        colors: ["#FFFFFF"],
        sizes: ["US 8", "US 9"],
        brand: { id: "b16", name: "Core Street", logoUrl: "" },
        brandId: "b16",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: true,
        isPromotion: false,
        stock: 10
    },

    // ================= PROMOTIONS (8) =================
    {
        id: "17",
        name: "Discount Runner",
        description: "High-performance running shoe now available at an incredible value. Perfect for daily training and casual wear.",
        price: 1200,
        discountPrice: 850,
        images: ["/images/nb_shoe_1.png", "/images/adidas_shoe_1.png", "/images/nike_shoe_1.png"],
        colors: ["#B3B3B3", "#FF4444", "#4444FF"],
        sizes: ["37", "38", "39", "40"],
        brand: { id: "b17", name: "Speed Line", logoUrl: "" },
        brandId: "b17",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 7
    },
    {
        id: "18",
        name: "Promo Hoodie",
        description: "Warm hoodie on sale.",
        price: 600,
        discountPrice: 400,
        images: ["/images/hero-bg.png"],
        colors: ["#222222"],
        sizes: ["M", "L"],
        brand: { id: "b18", name: "Heat Wear", logoUrl: "" },
        brandId: "b18",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 13
    },
    {
        id: "19",
        name: "Sale Dunk Style",
        description: "Street sneaker at promotional price.",
        price: 1050,
        discountPrice: 780,
        images: ["/images/nike_dunk_1.png"],
        colors: ["#000000"],
        sizes: ["US 8", "US 9"],
        brand: { id: "b19", name: "Urban Kicks", logoUrl: "" },
        brandId: "b19",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 9
    },
    {
        id: "20",
        name: "Clearance Trainer",
        description: "Last season performance shoe.",
        price: 1300,
        discountPrice: 900,
        images: ["/images/adidas_shoe_1.png"],
        colors: ["#FFFFFF"],
        sizes: ["US 10"],
        brand: { id: "b20", name: "Active Zone", logoUrl: "" },
        brandId: "b20",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 5
    },
    {
        id: "21",
        name: "Sale Hoodie",
        description: "Soft cotton hoodie discount.",
        price: 520,
        discountPrice: 360,
        images: ["/images/hero-bg.png"],
        colors: ["#B3B3B3"],
        sizes: ["S", "M"],
        brand: { id: "b21", name: "Softline", logoUrl: "" },
        brandId: "b21",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 17
    },
    {
        id: "22",
        name: "Promo Classic",
        description: "Classic sneaker deal.",
        price: 950,
        discountPrice: 700,
        images: ["/images/nike_shoe_1.png"],
        colors: ["#FFFFFF"],
        sizes: ["US 9"],
        brand: { id: "b22", name: "StepUp", logoUrl: "" },
        brandId: "b22",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 8
    },
    {
        id: "23",
        name: "Discount Jogger",
        description: "Comfort jogger reduced price.",
        price: 450,
        discountPrice: 300,
        images: ["/images/hero-bg.png"],
        colors: ["#1C1C1C"],
        sizes: ["M", "L"],
        brand: { id: "b23", name: "Relax Co", logoUrl: "" },
        brandId: "b23",
        categoryId: "c2",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 14
    },
    {
        id: "24",
        name: "Final Sale Sneaker",
        description: "Limited stock sneaker on sale.",
        price: 1100,
        discountPrice: 820,
        images: ["/images/nb_shoe_1.png"],
        colors: ["#B3B3B3"],
        sizes: ["US 10"],
        brand: { id: "b24", name: "Last Call", logoUrl: "" },
        brandId: "b24",
        categoryId: "c1",
        isFeatured: false,
        isNewArrival: false,
        isPromotion: true,
        stock: 4
    }
];

export const categories = [
    { id: "740e8400-e29b-41d4-a716-446655440000", name: "Sneakers", slug: "sneakers", image: "" },
    { id: "740e8400-e29b-41d4-a716-446655440001", name: "Clothing", slug: "clothing", image: "" },
    { id: "740e8400-e29b-41d4-a716-446655440002", name: "Accessories", slug: "accessories", image: "" },
]

export const brands = [
    { id: "b1", name: "Nike", logoUrl: "" },
    { id: "b2", name: "Adidas", logoUrl: "" },
    { id: "b3", name: "New Balance", logoUrl: "" },
    { id: "b4", name: "Nike SB", logoUrl: "" },
    { id: "b5", name: "Essentials", logoUrl: "" },
    { id: "b6", name: "Nike Sportswear", logoUrl: "" },
    { id: "b7", name: "Urban Supply", logoUrl: "" },
    { id: "b8", name: "Street Core", logoUrl: "" },
    { id: "b9", name: "RunLab", logoUrl: "" },
    { id: "b10", name: "Athletic", logoUrl: "" },
    { id: "b11", name: "Streetwear", logoUrl: "" },
    { id: "b12", name: "Athletic", logoUrl: "" },
    { id: "b13", name: "Streetwear", logoUrl: "" },
    { id: "b14", name: "Athletic", logoUrl: "" },
    { id: "b15", name: "Streetwear", logoUrl: "" },
    { id: "b16", name: "Athletic", logoUrl: "" },
    { id: "b17", name: "Streetwear", logoUrl: "" },
    { id: "b18", name: "Athletic", logoUrl: "" },
    { id: "b19", name: "Streetwear", logoUrl: "" },
    { id: "b20", name: "Athletic", logoUrl: "" },
    { id: "b21", name: "Streetwear", logoUrl: "" },
    { id: "b22", name: "Athletic", logoUrl: "" },
    { id: "b23", name: "Streetwear", logoUrl: "" },
    { id: "b24", name: "Athletic", logoUrl: "" },
]

export const TYPES_VERSION = '1.0'
